# Generated by Django 5.1.1 on 2024-10-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('capa_tcc', models.ImageField(blank=True, null=True, upload_to='tcc_covers/')),
                ('status', models.CharField(choices=[('em_ativo', 'Ativo'), ('concluido', 'Concluído')], default='Ativo', max_length=20)),
                ('data_entrega', models.DateField()),
                ('autores', models.ManyToManyField(limit_choices_to={'papel': 'orientando'}, related_name='teste_autores', to='app_tcc.user')),
                ('orientador', models.ForeignKey(limit_choices_to={'papel': 'orientador'}, on_delete=django.db.models.deletion.CASCADE, related_name='teste_orientador', to='app_tcc.user')),
            ],
        ),
    ]
