# Generated by Django 5.1.1 on 2024-10-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
